CREATE TABLE users (
                       id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name            VARCHAR2(120)       NOT NULL,
                       email           VARCHAR2(180)       NOT NULL UNIQUE,
                       password_hash   VARCHAR2(255)       NOT NULL,
                       role            VARCHAR2(20)        DEFAULT 'USER' NOT NULL,
                       zip_code        VARCHAR2(8),
                       city            VARCHAR2(120),
                       state           VARCHAR2(2),
                       created_at      TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,

                       CONSTRAINT chk_users_role CHECK (role IN ('ADMIN', 'USER'))
);