CREATE TABLE contracts (
                           id              NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           gig_id          NUMBER          NOT NULL REFERENCES gigs(id),
                           hirer_id        NUMBER          NOT NULL REFERENCES users(id),
                           status          VARCHAR2(20)    DEFAULT 'REQUESTED' NOT NULL,
                           created_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

                           CONSTRAINT chk_contracts_status CHECK (status IN ('REQUESTED', 'ACCEPTED', 'COMPLETED', 'CANCELLED'))
);
CREATE INDEX idx_contracts_gig_id ON contracts(gig_id);
CREATE INDEX idx_contracts_hirer_id ON contracts(hirer_id);