CREATE TABLE gigs (
                      id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      provider_id     NUMBER              NOT NULL REFERENCES users(id),
                      title           VARCHAR2(150)       NOT NULL,
                      description     CLOB                NOT NULL,
                      category        VARCHAR2(80)        NOT NULL,
                      price           NUMBER(10,2)        NOT NULL,
                      status          VARCHAR2(20)        DEFAULT 'ACTIVE' NOT NULL,
                      created_at      TIMESTAMP           DEFAULT SYSTIMESTAMP NOT NULL,

                      CONSTRAINT chk_gigs_status CHECK (status IN ('ACTIVE', 'PAUSED', 'CLOSED')),
                      CONSTRAINT chk_gigs_price CHECK (price >= 0)
);

CREATE INDEX idx_gigs_provider_id ON gigs(provider_id);
CREATE INDEX idx_gigs_status ON gigs(status);